### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by brent-dxw**
- Update php-cs-fixer to ^2.0 to allow running on php > 7.2
- Do composer update to update phpseclib to resolve security alert
- Update README (vendor.phar approach no longer used)
- Update version number in main plugin file

- [X] Version number has been bumped

### CODE REVIEW

**Comment by RobjS** [comment]
@brent-dxw Would it be possible to split the various types of changes here (e.g. updating PHP CS fixer, running the fixer,  updating other dependencies etc.) out into separate commits? That would make it easier to see what's happening where.

**Comment by brent-dxw** [comment]
@RobjS that's done...

**Comment by RobjS** [comment]
Thanks @brent-dxw, that's miles better!

I feel like the PR template for this repo is actually a bit misleading - we probably don't want to be bumping the version number each time. Instead, we should add a changelog (as per https://github.com/dxw/tech-team-rfcs/blob/main/rfc-019-use-changelogs-to-track-changes.md), then do PRs for version bumps.

We should also migrate the CI to GitHub actions rather than Travis.

Up to you whether you want to tackle some of that in this PR - if not, I'd be happy to approve it without the version bump, and we could deal with those other issues in separate PRs.

**Comment by brent-dxw** [comment]
Thanks @RobjS I reckon let's get this merged to sort out the security issue

**Review by RobjS — APPROVED** [review]

**Pull request merged**
